env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
  - "error"
  - "tab"
  no-tabs: 0
  import/extensions: 0
  no-console: 0
